version: '3'

networks:
  web:
    external: true
  internal:
    external: false
services:
  edata-site:
    container_name: edata-site
    image: jkaninda/nginx-php-fpm:8.2
    restart: unless-stopped
    networks:
      - internal
      - web

    volumes:
      - ./src:/var/www/html
      # - ./conf/nginx/nginx-site.conf:/var/www/html/conf/nginx/nginx-site.conf
    ports:
      - 80
    labels:
       - "traefik.enable=true"
       - "traefik.http.routers.edata-site.rule=Host(`www.edata.africa`, `edata.africa`)"
       - "traefik.http.routers.edata-site.tls.certresolver=lets-encrypt"
       - "traefik.port=80"
       - "traefik.docker.network=web"


